# Generated by Django 4.2.2 on 2023-06-30 11:39

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media/', validators=[pages.models.validate_image_file]),
        ),
    ]
